### ISSUE TITLE
Readme.md Wrong Information

### ISSUE THREAD

**Issue by Kippenhof** [BadlionClient/BadlionClientModAPI#11]
The Point "ItemPhysic" is Wrong. "Item Physics" Woked. Idk how to Create an Pull Request but let the message count as one

**Comment by PSNRigner** [comment]
Hello,

Yes, the mod name changed recently, that's why.

I need to update the full documentation very soon.

**Comment by PSNRigner** [comment]
Has been fixed, thanks for reporting :)
