### ISSUE TITLE
Cannot disable the "flySpeed" feature of Badlion Client

### ISSUE THREAD

**Issue by AMDBartek** [BadlionClient/BadlionClientModAPI#12]
Using the example config (from readme.md) to disable flySpeed doesn't work, I have tried everything I can think of and I cannot disable the Fly Speed feature of the Badlion client, help would be appreciated.

Edit to clarify: I can still use flySpeed in Badlion client even though it is disabled with the BadlionClientModAPI.

**Comment by PSNRigner** [comment]
Hello,

I think the documentation is just wrong, since we moved flySpeed to another mod. Will fix that as soon as possible, thanks for reporting.

**Comment by AMDBartek** [comment]
Hello, After some more testing I have found that it can be disabled (using the example config), however there is no indicator in the Badlion client saying it was disabled. So I suggest adding an indicator in the client saying that Fly Speed is disabled, other than that I am going to close this issue, but feel free to re-open if needed.

**Comment by PSNRigner** [comment]
Alright, thanks for your feedback :)
