### ISSUE TITLE
[03:29:40 ERROR]: Could not pass event PlayerJoinEvent to BadlionClientModAPI v1.0 

### ISSUE THREAD

**Issue by Schmilko** [BadlionClient/BadlionClientModAPI#14]
https://hatebin.com/qklmjekvig
I need help, a player is having trouble joining, keeps timing out

**Comment by PSNRigner** [comment]
Hello,

Can you show your plugin config ? It shouldn't error on that line.

**Comment by PSNRigner** [comment]
Might be invalid config. Closing this since no answer from the author.
