### ISSUE TITLE
default config doesnt generate

### ISSUE THREAD

**Issue by AlekseyTitov99** [BadlionClient/BadlionClientModAPI#15]
When you first install the bukkit version, the default config doesnt generate

**Comment by LaserSlimeHD** [comment]
Can confirm. While this might be intentional, writing a config by hand is really a pain. Please fix.

**Comment by qfoxb** [comment]
Happening to me too.

**Comment by PSNRigner** [comment]
Thanks for the report, I'll make an internal ticket to adress this issue!

**Comment by PSNRigner** [comment]
Hey, I just fixed that issue in [1.2.3](https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/1.2.3)
