### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by LaserSlimeHD** [BadlionClient/BadlionClientModAPI#17]
The documentation is missing a lot of the newly added modules like Pack Tweaks and BlockInfo.
Also you can't disable some sub options for newly added modules. This is especially important for Pack Tweaks. Every suboption should be customizable and documented.

**Comment by PSNRigner** [comment]
Thanks, I'm gonna update it 😄

**Comment by PSNRigner** [comment]
It has been updated with all the 3.0 additions! Have a nice day

**Comment by LaserSlimeHD** [comment]
> 
> 
> It has been updated with all the 3.0 additions! Have a nice day

Thank you! Is there now also support for disabling some settings like the different pack tweaks?

**Comment by PSNRigner** [comment]
Not yet, but there's an internal ticket for us to do it!
