### ISSUE TITLE
Auto-Kick Badlion Users

### ISSUE THREAD

**Issue by patrickcerny** [BadlionClient/BadlionClientModAPI#22]
Hey! It would be great to have a config option, to kick all players using the client.

**Comment by PSNRigner** [comment]
Hello, can you provide a use case of such a system ?

**Comment by patrickcerny** [comment]
Well it would be nice if you want to "force" players to play vanilla. Of course you could disable all features, but the person would still be able to join with the client. Have a nice day!

**Comment by PSNRigner** [comment]
Well there's #18 for disabling all Badlion related features, except FPS Boost, which is exactly like Vanilla, just with increased performance.

Right now there's no accurate (and 100% unspoofable) way of knowing if a client is using Badlion Client apart from using the anticheat, which wouldn't be a good solution in that case.

**Comment by patrickcerny** [comment]
Yeah okey, seems plausible that this "feature" is more nice to have than really needed!
