### ISSUE TITLE
Don't overwrite config on shutdown

### ISSUE THREAD

**Issue by Grizzly-ger** [BadlionClient/BadlionClientModAPI#25]
changes in the config on velocity (3.1.1) are only possible while the server is offline. I would like to change the config while server is running, so the changes will apply on next restart

**Comment by PSNRigner** [comment]
Hey, thanks for the report, we'll look into it (cc @arrayofc)

**Comment by PSNRigner** [comment]
Hey, has been fixed in https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/2.0.1 😃
