### ISSUE TITLE
Feature request: Make Badlion client detectable

### ISSUE THREAD

**Issue by VidTu** [BadlionClient/BadlionClientModAPI#27]
A method like `BadlionApi.isUsingBadlion(UUID/Player)` can be useful for detecting Badlion users for some purposes like saving bandwidth (not sending badlion packets to non-badlion users), suggesting using Badlion client, display user brand, etc.
This can be possibly done by changing client brand [`minecraft:brand` payload] (e.g. from `vanilla` to `badlion`) or registering a plugin (custom payload) channel via `minecraft:register`.

**Comment by VidTu** [comment]
I don't say this information should be trusted. Brand packets could be spoofed by anyone. This is just a convenience thing for displaying user stats (e.g. _approximate_ percentage of people using Badlion on your server) or sending `badlion:mods` custom payload packets only to users with Badlion.

**Comment by PSNRigner** [comment]
I'll think about it for our next update, will talk about it with the team 😃

**Comment by RichardDorian** [comment]
```java
    @Override
    public void onPluginMessageReceived(String channel, Player player, byte[] bytes) {
        if (channel.equals("BungeeCord")) {
            DataInputStream dataInputStream = new DataInputStream(new ByteArrayInputStream(bytes));

            try {
                if (dataInputStream.readUTF().equals("heartbeat")) {
                    switch (dataInputStream.readUTF()) {
                        case "true":
                            // Your code here
                            // User is using Badlion AntiCheat
                            break;

                        case "false":
                            // Your code here
                            // User is not using Badlion AntiCheat
                            break;
                    }
                }
            } catch (IOException ignored) {

            }
        }
    }
```
I saw this as an example. This is also spoofable. Is there a real way to know from something trustworthy?

**Comment by TrasherMC** [comment]
It would be great if BLC could send a modified client brand string on login (Just like Lunar does) - Since the "FPS Boost" feature breaks rendering of custom fonts. This is a huge problem for servers that rely on resourcepacks and custom fonts, therefore having a modified client brand string when playing with BLC could allow server owners to:
- Warn players that said feature should be disabled to not encounter glitched text rendering
- Send messages that do not contain custom fonts

**Comment by PSNRigner** [comment]
> ```java
>     @Override
>     public void onPluginMessageReceived(String channel, Player player, byte[] bytes) {
>         if (channel.equals("BungeeCord")) {
>             DataInputStream dataInputStream = new DataInputStream(new ByteArrayInputStream(bytes));
> 
>             try {
>                 if (dataInputStream.readUTF().equals("heartbeat")) {
>                     switch (dataInputStream.readUTF()) {
>                         case "true":
>                             // Your code here
>                             // User is using Badlion AntiCheat
>                             break;
> 
>                         case "false":
>                             // Your code here
>                             // User is not using Badlion AntiCheat
>                             break;
>                     }
>                 }
>             } catch (IOException ignored) {
> 
>             }
>         }
>     }
> ```
> 
> I saw this as an example. This is also spoofable. Is there a real way to know from something trustworthy?

This is only valid when using the Badlion Anticheat, and it's not spoofable since BungeeCord blocks that plugin channel if sent by the client.

**Comment by PSNRigner** [comment]
> It would be great if BLC could send a modified client brand string on login (Just like Lunar does) - Since the "FPS Boost" feature breaks rendering of custom fonts. This is a huge problem for servers that rely on resourcepacks and custom fonts, therefore having a modified client brand string when playing with BLC could allow server owners to:
> 
> * Warn players that said feature should be disabled to not encounter glitched text rendering
> * Send messages that do not contain custom fonts

I'll see what I can do about it, but yeah wouldn't 100% rely on that since it can be spoofable. Will also ask the team about that custom font issue with fps boost, I personally wasn't aware.

**Comment by Budderman18** [comment]
i'm going to bump this. I have a plugin that sends a special message to those using Badlion warning them that most mods are blocked. THis stooped working when badlion removed the brand packet sent and reads as vanilla instead. At least re-add this if you arent going to add something built-in to this so we can get rough estimates on badlion usage.

**Comment by Rigner** [comment]
Hello,

This feature will be available in Badlion Client 4.3, which will come out in the next few weeks / months. It is currently in testing internally.

**Comment by OfficialCRUGG** [comment]
@Rigner Will this be solved through custom packets / your library (which would be unnecessarily overcomplicated for this) or will it just be a custom client brand like with essentially all other clients?

**Comment by Rigner** [comment]
> @Rigner Will this be solved through custom packets / your library (which would be unnecessarily overcomplicated for this) or will it just be a custom client brand like with essentially all other clients?

For now it will just be the brand packet.

A bit later we will also update this ModApi to only send Badlion packets to players that are detected as Badlion players, to not send packets to other ones.

Depending on how it goes and if some servers request it, we could implement more stuff in the api :)

**Comment by OfficialCRUGG** [comment]
Alright, thanks for this! The brand packet will really be a massive help!

**Comment by Rigner** [comment]
This went live last week in Badlion Client 4.3. 😃
