### ISSUE TITLE
Failed to find EntityPlayer class in Paper Server 1.19

### ISSUE THREAD

**Issue by Doc94** [BadlionClient/BadlionClientModAPI#32]
Log: https://paste.gg/p/anonymous/0abdc7484a254e7381833382d380fef9
Server Version: Paper version git-Paper-77 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 44b6869)

**Comment by PSNRigner** [comment]
Hello, please use the Bukkit-1.17 version of the plugin for 1.17+ support.
