### ISSUE TITLE
How to enabled survival mods

### ISSUE THREAD

**Issue by SmallishMink34** [BadlionClient/BadlionClientModAPI#37]
I have my personal server with my friends, i want to enabled everythings in the survival tab. I don't find somethings to do it with your api. I try to enable survival and each things but without success

**Comment by PSNRigner** [comment]
Hello, in theory all you need to do once the plugin is installed is to run `/survivalapi` and enable the features you want. The survival mod is only for recent minecraft versions through, 1.17 and above.

Make sure you installed the right plugin version, the bukkit one with 1.17 in the name.

------------------------

French

Bonjour, en théorie vous avez juste à utiliser `/survivalapi` puis activer les différentes fonctionnalités que vous souhaitez utiliser. Par ailleurs, le mod Survival est uniquement disponible dans les versions récentes de Minecraft, à partir de la 1.17.

Vérifiez que vous avez bien installé la bonne version de notre plugin, celle pour Bukkit 1.17+.
