### ISSUE TITLE
/survivalapi not working

### ISSUE THREAD

**Issue by Kaito099** [BadlionClient/BadlionClientModAPI#44]
Hey im trying to allow the survival features on my server but when i execute the /survivalapi command nothing happens even when i restart the server. Can you help me to get it to work?
It is minecraft 1.21.

**Comment by Rigner** [comment]
Hello,

Could you provide more context about the issue, like any server log showing an error or something else ?

Did you install the right plugin ? Recent MC versions need the "1.17" plugin to be installed. We'll maybe rename the plugins to make that more clear.

**Comment by Kaito099** [comment]
That was my problem, the error was that this command does not exists.
And i used the "1.17" plugin.

Unfortunately i do not have the server anymore.

**Comment by Rigner** [comment]
Alright thanks, I guess the plugin failed to load then. Gonna try to reproduce it myself.

**Comment by Kaito099** [comment]
Does the plugin only work on Bukkit or does it work on Paper to?

**Comment by Kaito099** [comment]
Got it to work now on a new server, thanks for your help
