### ISSUE TITLE
Can't disable shakingIntensity

### ISSUE THREAD

**Issue by Nekoli** [BadlionClient/BadlionClientModAPI#45]
Hello, 

It is currently not possible to adjust/disable shakingIntensity, so even if you disable noShake, players can just set their shakingIntensity to 0 for the same effect.

Could the option to adjust/disable shakingIntensity be added, if there's not already to do so?

Thank you.

**Comment by Rigner** [comment]
Hey, thanks for reporting this issue!

After a quick look at the code, it seems that you're right and the slider option is overriding the enabled flag.

I'm forwarding this to the team so we can fix it as soon as possible, we're most likely gonna add a new option to toggle that behaviour.

**Comment by Rigner** [comment]
Hello, an update has been deployed yesterday with a fix to this issue. You can now disable this behaviour by adding the following:
```json
"shakeIntensity": {
    "disabled": true
}
```
