### ISSUE TITLE
[Bug Report] removeHitDelay no longer working

### ISSUE THREAD

**Issue by theFoxley** [BadlionClient/BadlionClientModAPI#46]
The plugin was working fine, and since a few days it does not work and the players can no longer enjoy the removeHitDelay feature.
I tested so much things in order to get it working but nothing works.
Tested on different spigots, tested it with or without plugins, and still it does not work
It does not work on Paper 1.8 (or any spigot), and only Badlion-API.
No error in the console at all.

Reproduction steps
1. Download Paper 1.8
2. Download latest BadlionClientModeAPI
2b. Set removeHitDelay: force: true
3. Download https://www.spigotmc.org/resources/cps-alert-original.19181/
4. Download an autoclick that can go above 21 cps
5. Start server and game
6. Start autoclicking while hitting air with more than 21 cps, see that the server only see 20cps constantly (so the plugin is not working because we have still the hit delay)
7. Go in creative mode and do the same thing
8. See that the cps go more than 21 cps

Client Version
1.8

Platforms
Spigot / Bukkit

Server Version
1.8

Screenshots
Only two plugins on Paper 1.8 :
https://www.noelshack.com/2024-41-2-1728424769-image6.png

Clicking at 60 cps in the air while in survival mode only show 20 cps serverside (so the plugin is not working because we have still the hit delay)
https://www.noelshack.com/2024-41-2-1728423773-image2.png

Clicking at 60 cps in the air while in creative mode show 60 cps serverside
https://www.noelshack.com/2024-41-2-1728423773-image3.png

Clicking at 60 cps on an entity while in survival mode show 60 cps serverside
https://www.noelshack.com/2024-41-2-1728423773-image4.png

**Comment by Rigner** [comment]
Hey, thanks for the report!

I'm gonna forward this to the team to review any recent change that may have caused the issue... Let's hope for a quick fix!

**Comment by Rigner** [comment]
Hello, an update has been deployed yesterday with should fix this issue. If you can reproduce it, please reply to this github issue and we'll investigate further.
